### ISSUE TITLE
Error on MetricReportDefition PATCH 

### ISSUE THREAD

**Issue by jcsnascimento** [sailfishdell/sailfish#12]
Hi,

I'm trying to PATCH a metric report definition like **redfish/v1/TelemetryService/MetricReportDefinitions/CPUSensor** to change _RecurrenceInterval_ and _MetricReportDefinitionEnabled_ values

{  
"Schedule": {
    "RecurrenceInterval": "T90"
  },
 "MetricReportDefinitionEnabled": false
}

I'm able to do this PATCH  resquest  to **RedfishMockupServer**, but the **sailfish** always returns _HTTP 401 - Unauthorized_ using Administrator/password basic auth header.

**Comment by windsparks33** [comment]
Hi @jcsnascimento,
Looking into your issue now.

**Comment by jcsnascimento** [comment]
thanks @windsparks33

**Comment by ahfalves** [comment]
Hi @windsparks33, do you have any updates on your investigation?
Thanks

**Comment by superchalupa** [comment]
Two things:

when you upload the resource initially, you need to set PATCH permissions in the upload script for that resource. That will address the unauthorized error. The next issue is there isn't a handler to take the updated value for that uri, so that will require a little bit of code change on the back end.

**Comment by superchalupa** [comment]
The get-tree.sh script formats a RedfishResource:Create command, which specifies privileges:
 37      echo \"Privileges\": { \"GET\": [\"Unauthenticated\"] }, >> $TMP

This must be updated for this specific resource to add "PATCH": ["Unauthenticated"] to the hash as well.

Next, in the actual resource, you'll need to change the patch-able attributes to add an @meta tag to tell sailfish how to handle the patch.

**Comment by superchalupa** [comment]
We will need to write a new @meta "plugin" to handle the patch request, but the code is extraordinarily straightforward. I'll share details with @windsparks33 and should be able to knock this out soon.

**Comment by windsparks33** [comment]
Hi, 
apologizes for the delay, now giving this task priority.

@jcsnascimento 
Can you provide steps on how to setup the environment you have?  
I can test these changes on it to touch all bases.

**Comment by windsparks33** [comment]
Hi @jcsnascimento,

Made an assumptions about your request.  
- get-tree.sh is used to create the tree

With assumption, got a fix for you, testing complete.  Just need to code review and will have it out to you.

**Comment by jcsnascimento** [comment]
Hi @windsparks33, sorry for delay (all messages from github was in spam folder).
and yes, get-tree was used to create the tree.
Thanks!

**Comment by windsparks33** [comment]
@jcsnascimento 
Spam folders are always such trouble makers!  

Code collab is approved and code is pushed to github.

Example of how to enable PATCH per property.
          file: Mockup-Datasets/Server-PowerEdge-C6320/redfish/v1/TelemetryService/MetricReportDefinitions/PlatformPowerUsage/index.json
           line: "MetricReportDefinitionEnabled@meta": {"PATCH": {"plugin":"MRD"}},

get-tree.sh is modified slightly to enable PATCH privileges on all URLs.  

Let me know if everything works well for you. 
After three days, I'll assume everything went well if there is no word and close the issue.
