### ISSUE TITLE
get-tree.sh is hardcoded to only Systems and Chasis.

### ISSUE THREAD

**Issue by SailM23** [sailfishdell/sailfish#4]

**Comment by SailM23** [comment]
Get-tree.sh is currently hardcoded to chassis and systems. Changed to recursively find index.json. Below is the get-tree.sh code:

#!/bin/bash

set -x
set -e

TREE=/home/dcoffman/14G

unset HTTP_PROXY HTTPS_PROXY http_proxy https_proxy

TMP=$(mktemp /dev/shm/curl_input.XXXXXXXXX)

CURLCMD="curl "
prot=${prot:-http}
host=${host:-localhost}
port=${port:-8080}

URL=$prot://$host:$port

add_element()
{
	directory=$(dirname $1)
	URI=${directory#${TREE}}
	URI=${URI%/}
	UUID=$(uuidgen)
	ELEMENT="$(cat $1)"
	TYPE=$(echo $ELEMENT | jq '.["@odata.type"]')
	CONTEXT=$(echo $ELEMENT | jq '.["@odata.context"]')

	size=$(echo $ELEMENT | wc -c)
	echo SIZE=$size

     echo "{"  > $TMP
     echo \"ID\": \"$UUID\", >> $TMP
     echo \"ResourceURI\": \"${URI}\", >> $TMP
     echo \"Type\": $TYPE, >> $TMP
     echo \"Context\": $CONTEXT,>> $TMP
     echo \"Privileges\": { \"GET\": [\"Unauthenticated\"] }, >> $TMP
     echo \"Properties\": >> $TMP
     cat $1 >> $TMP
     echo "}" >> $TMP
			
	$CURLCMD $URL/api/RedfishResource%3ACreate  -d @$TMP
    echo  RET=$?
}

for signal in 1 2 3 5 6 15;do
        trap "rm -f $TMP" $signal
done


for i in $(find \
	${TREE}/redfish/v1 \
	-type f -name index.json)
do
	echo $i
	add_element $i
done
 
rm -f $TMP

**Comment by superchalupa** [comment]
Please send a PR for this change.

**Comment by superchalupa** [comment]
Please note that you must filter out some URLs, as they need to be handled by sailfish. If you upload new content for them, they will fail.

This includes things like SessionService (logins will break) and EventService.

**Comment by windsparks33** [comment]
tested this past week.  Looks good.
